:!s:
== Specific features and functionalities

This section covers ideas relating to usability issues and features lacking in the existing tools.

=== Single record retrieval

Based on the purpose of live federated searches across networks, the BPS allows accessing individual records or a subset of records instead of whole datasets.

:!n:
[horizontal]
{counter:c}.{counter:s}.{counter:n}.:: Keeping in mind the trend towards versioned exports of entire datasets: Is this still needed?

=== Standards: Darwin Core/ABCD (+GGBN/EFG)/MIxS/customized sets of terms?

The BPS can be used with an arbitrary XML schema, but is centred around the ABCD standard and its extensions; the IPT is intrinsically connected with Darwin Core.

:!n:
[horizontal]
{c}.{counter:s}.{counter:n}.:: How close should the tool be coupled with the standard(s) supported, keeping in mind that a complete decoupling would limit certain features such as data validation?
{c}.{s}.{counter:n}.:: Since both Darwin Core and ABCD need to be supported: Will there be two mappings if you want to provide data in both standards? Or will there be one mapping and the output will be converted into another standard upon request (as implemented now in the BPS, which transforms ABCD documents into Darwin Core archives).

=== Input formats: CSV, relational databases?

Typical input data for the IPT are delimited text files (with the possibility to also import data from simple database tables and views), whereas the BPS was designed to load data from (potentially complex) relational databases.
This is connected with the specifics of the data standards – Darwin Core being rather flat, ABCD having a hierarchical structure with many repeatable elements.

:!n:
[horizontal]
{c}.{counter:s}.{counter:n}.:: Should the new tool support both source types?
{c}.{s}.{counter:n}.:: Are there any other input formats we should support? Frictionless data?

=== Output formats: DwC-A, XML, RDF, Frictionless data, JSON?

The IPT produces Darwin Core archives that store delimited text files, one core file (typically an occurrence) and potentially several extension(s) connected through the star schema.
Due to its XML nature, the ABCD standard used by the BPS allows 1:n relations between entities other than the occurrence.

:!n:
[horizontal]
{c}.{counter:s}.{counter:n}.:: With the limitations of the star schema, should DwC archives evolve into Frictionless data packages?
{c}.{s}.{counter:n}.:: Is XML still a desirable output format?
{c}.{s}.{counter:n}.:: Other output formats – RDF, JSON, Catalogue of Life data packages? If yes: Should these be produced by the tool natively or could these be generated from other formats on the fly, e.g. by using Frictionless data?

=== Versioning

The rising importance of proper citing requires that changes in the data can be tracked through versioning.

// No question, but counter still needs incrementing.
{counter2:s}

=== Support of incremental updates

Citizen science has shifted dataset sizes into hundreds of millions of records, with updates putting a heavy load on providers and harvesters.

:!n:
[horizontal]
{c}.{counter:s}.{counter:n}.:: Are incremental updates that just hold updated and new records required or not an issue?

=== Dataset descriptions (Metadata)

The IPT supports metadata authoring to the EML standard, extended to support some basic collection descriptions from the (original) NCD standard.

:!n:
[horizontal]
{c}.{counter:s}.{counter:n}.:: Is EML still the most appropriate format for metadata, and is the profile supported by the IPT adequate. Should it describe the data files in the EML to enable wider interoperability with e.g. ILTER networks?
{c}.{s}.{counter:n}.:: There is potential to derive metadata, such as taxonomic, temporal and geographic scope from data. To what extent should metadata be derived from the data?
{c}.{s}.{counter:n}.:: IPT users have reported frustration in the need to re-enter contacts (people) repeatedly. Improving the usability of this section of metadata is desired (e.g. reusing existing details, or drawing information from public registries like the ORCID system). What other usability issues in metadata authoring should be addressed?
